---
- name: Create unprivledged folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/{{cpp_software_directory}}"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"

- name: Download CLion Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/cpp/CLion-{{cpp_clion_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{cpp_download_directory}}/clion-{{cpp_clion_version}}.tar.gz"
      mode: 0444
  when: cpp_clion_install

- name: Uncompress CLion Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{cpp_download_directory}}/clion-{{cpp_clion_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{cpp_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{cpp_software_directory}}/clion-{{cpp_clion_version}}/build.txt"
  when: cpp_clion_install

- name: Create Softlink To CLion
  become: no
  file:
      src: "{{ansible_user_dir}}/{{cpp_software_directory}}/clion-{{cpp_clion_version}}"
      dest: "{{ansible_user_dir}}/{{cpp_software_directory}}/clion"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: cpp_clion_install

- name: Create Desktop Icon For CLion
  become: no
  template:
      src: "templates/clion.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/clion.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: cpp_clion_install

